import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  
  useEffect(()=>{
    // if("serviceWorker" in window.navigator) {
    //   navigator.serviceWorker
    //   .register("/sw.js")
    //   .then(
    //     function (registration) {
    //       console.log("Service Worker registration successful with scope: ", registration.scope);
    //     })
    //     .catch(function (err) {
    //       console.log(err);
    //     })
    // }
  },[])

  return (
    <>
      <Head>
        <title>New PWA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div style={{width:'95vw'}}>
          <h1 style={{textAlign:'center'}}>
            Landing Page!
          </h1>
        </div>
      </main>
    </>
  )
}
